baseURL: https://carloscds.net/
theme: pure
title: Carlos dos Santos
defaultContentLanguage: en  # en/zh/...
footnoteReturnLinkContents: ↩
removePathAccents : true
hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
googleAnalytics: "UA-8863591-6"
permalinks: 
  posts: /:year/:month/:filename/
  

taxonomies:
    category : categories
    tag : tags
    series : series
    
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts/
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 5

    - identifier: contact
      name: Contact
      title: Contact
      url: mailto:cdssoftware@hotmail.com?subject=Contato_Blog
      weight: 6

    - identifier: videos
      name: Videos
      title: Videos
      url: /videos/
      weight: 7


params:
  since: 2008
  dateFormatToUse: ""
  enablePostCopyright: false
  disqusShortname: "carloscds"
  
  # the directory under content folder that you want to render
  mainSections: ["posts"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: true #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["csharp","python", "javascript"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js

  # Allows you to specify an override stylesheet
  # put custom.css in $hugo_root_dir/static/
  # customCSS: css/custom.css

  menuIcons:
    enable: true  
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill
    contact: icon-project
    videos: icon-book-fill

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: https://avatars0.githubusercontent.com/u/1697221?s=460&u=409a6ac4e0cca9f7302962ae6f6e375507c7d38f&v=4
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: Carlos dos Santos
    author_title: Technology and Code
    author_description: Code for Life!
    location: Developer world!
    follow: https://www.carloscds.net
    # Social Links
    social:
      links:
        github: https://github.com/carloscds
        twitter: https://twitter.com/cdssoftware
        facebook: https://www.facebook.com/carloscds
        rss: /index.xml
      link_tooltip: true # enable the social link tooltip, options: true, false
  # Site
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    title: Carlos dos Santos - Developer Blog
    favicon: favicon.ico
    board: <p></p> 

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true 
    sites: facebook,twitter,linkedin

  # Comment
  comment:
    type:  disqus
    disqus: carloscds

  # PV
  pv:
    busuanzi:
      enable: false # 不蒜子统计
    leancloud:
      enable: false # leancloud统计
      app_id: # leancloud <AppID>
      app_key: # leancloud <AppKey>

  # wordcount
  postCount:
    enable: true
    wordcount: true # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: theme-blue # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - category
    - tag
    - recent_posts
    